# Generated by Django 2.0.13 on 2019-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('updated_time', models.DateTimeField()),
                ('reactions', models.TextField()),
            ],
        ),
    ]
