# Generated by Django 2.0.13 on 2019-09-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gmail_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_given', models.IntegerField()),
                ('reaction_received', models.IntegerField()),
                ('reaction_type', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmail_authentication.User')),
            ],
        ),
    ]
