# Generated by Django 2.0.13 on 2019-09-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gmail_authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_given', models.IntegerField(default=0)),
                ('reaction_received', models.IntegerField(default=0)),
                ('reaction_type', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmail_authentication.User')),
            ],
        ),
    ]
