# Generated by Django 2.2.5 on 2019-09-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gmail_authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('comment', models.TextField()),
                ('datetime_voted', models.DateTimeField(auto_now_add=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmail_authentication.Department')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmail_authentication.User')),
            ],
        ),
    ]
