# Generated by Django 2.0.13 on 2019-09-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='datetime_vote',
            new_name='datetime_voted',
        ),
        migrations.AddField(
            model_name='votes',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
