# Generated by Django 2.2.5 on 2019-09-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='department_name',
        ),
    ]
