# Generated by Django 2.2.4 on 2019-09-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='comment',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
