# Generated by Django 2.2.4 on 2019-09-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_votes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='datetime_vote',
            new_name='datetime_voted',
        ),
    ]
