# Generated by Django 2.2.4 on 2019-09-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_authentication', '0002_user_profile_picture'),
        ('vote', '0003_auto_20190902_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='department_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gmail_authentication.Department'),
            preserve_default=False,
        ),
    ]
