# Generated by Django 2.2.4 on 2019-09-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
