# Generated by Django 2.2.5 on 2019-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
    ]
